"""index created_at on posts and users

Revision ID: 1c789fbd8a60
Revises: 36f50c1517c0
Create Date: 2026-07-01 15:33:56.581168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c789fbd8a60'
down_revision: Union[str, Sequence[str], None] = '36f50c1517c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_posts_created_at', table_name='posts')
    # ### end Alembic commands ###
